# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce4209b41b500ae59de846f07a4ed3eca19076ea65ec040119769f4118761ea9a87fcc1e3600b2ad082328b33278b2678ecf8f3638840144d4888b2b57d0b128

test:
  secret_key_base: 25fc1853b69bd7ba9fbfedd80f1f44358ca82e63e055d8867837b2a01ca1d04f45a5ecd98afc15f696a141dcdbf59d8e34c7e09287a0a95647b882e63da57bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
